language: c
sudo: required

env:
 - CABALVER=1.20 GHCVER=7.8.4

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - travis_retry sudo apt-get install -y python-setuptools subversion tcl8.5
 - travis_retry sudo easy_install virtualenv

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - travis_retry virtualenv ~/llvmsandbox
 - travis_retry svn co http://llvm.org/svn/llvm-project/lnt/trunk ~/lnt
 - travis_retry ~/llvmsandbox/bin/python ~/lnt/setup.py install
 - travis_retry wget -O ~/test-suite.tar.xz http://llvm.org/releases/3.5.0/test-suite-3.5.0.src.tar.xz
 - travis_retry tar xvfJ ~/test-suite.tar.xz -C ~/
 - travis_retry git clone https://github.com/mlite/llvm_emp ~/llvm_emp

script:
 - cabal install --only-dependencies 
 - cabal configure -v2
 - cabal build
 - cabal sdist
